name: test-app
on: [push]
jobs:
  run-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.17.1'
      - run: go test ./... -race -timeout 2m